#' custom_tab_Narlal
#' @description An internal function used to define the layout of the tables generated by the package
#' @param df the data.frame containing the table
#' @param header the text that will appear as header of the table
#' @param footer the text that will appear as footer of the table
#' @keywords internal
#' @return a flextable containing the table
#' @export
#' @importFrom tibble %>%

custom_tab_Narlal <- function(df, header, footer){
  flextable::flextable(df) %>%
    flextable::add_header_lines(header) %>%
    flextable::add_footer_lines(footer) %>%
    flextable::bold(i = 1, part = "header") %>%
    flextable::hline_top(part = "header",
              border = officer::fp_border(color = "black",
                                 width = 2,
                                 style = "solid")) %>%
    flextable::hline(i = 1,
          part = "header",
          border = officer::fp_border(color = "black",
                             width = 0.25,
                             style = "solid")) %>%
    flextable::hline_top(part = "body",
              border = officer::fp_border(color = "black",
                                 width = 0.25,
                                 style = "solid")) %>%
    flextable::hline_bottom(part = "body",
                 border = officer::fp_border(color = "black",
                                    width = 0.25,
                                    style = "solid")) %>%
    flextable::hline_bottom(part = "footer",
                 border = officer::fp_border(color = "black",
                                    width = 0.25,
                                    style = "solid")) %>%
    flextable::border_inner_h(part = "body",
                   border = officer::fp_border(color = "black",
                                      width = 0.25,
                                      style = "dotted")) %>%
    flextable::autofit(part = "body") %>%
    flextable::bg(part = "body", bg = "#f5f5f5") %>%
    flextable::align(part = "all", align = "center") %>%
    flextable::align(j = 1, part = "all", align = "left")
}
#' customtab_defaults_Narlal
#' @description An internal function used to define the some defaults for the flextable used to produce the table of the package
#' @keywords internal
#' @return no direct returned values. Only setting flextable defaults
#' @export

customtab_defaults_Narlal <- function(){
  flextable::set_flextable_defaults(font.family = "Calibri",
                         font.size = 10,
                         border.color = "black")
}
#' Copy of ggcompetingrisks.cuminc but need to enable edition of a two layout (order of plotting and conf.int usinng lines)
#'
#' @param fit see ggcompetingrisks {survminer}
#' @param gnames see ggcompetingrisks {survminer}
#' @param gsep see ggcompetingrisks {survminer}
#' @param multiple_panels see ggcompetingrisks {survminer}
#' @param coef see ggcompetingrisks {survminer}
#' @param conf.int see ggcompetingrisks {survminer}
#'  @keywords internal
#' @return Returns an object of class gg.
#' @export
#'
#'
ggcompetingrisks.cuminc_narlal <- function(fit, gnames = NULL, gsep=" ",
                                           multiple_panels = TRUE, coef = 1.96, conf.int = FALSE) {

  if (!is.null(fit$Tests))
    fit <- fit[names(fit) != "Tests"]
  fit2 <- lapply(fit, `[`, 1:3)
  if (is.null(gnames)) gnames <- names(fit2)
  fit2_list <- lapply(seq_along(gnames), function(ind) {
    df <- as.data.frame(fit2[[ind]])
    df$name <- gnames[ind]
    df
  })
  time <- est <- event <- group <- NULL
  df <- do.call(rbind, fit2_list)
  df$event <- sapply(strsplit(df$name, split=gsep), `[`, 2)
  df$group <- sapply(strsplit(df$name, split=gsep), `[`, 1)
  df$std <- std <- sqrt(df$var)
  pl <- ggplot2::ggplot(df, ggplot2::aes(time, est, color=event))
  if (multiple_panels) {
    #in this line forcasts::fct:rev is introduced to invert the ordering of the plots. The problem is that the implicit factor in facet_wrap orders the levels alphabetically
    pl <- ggplot2::ggplot(df, ggplot2::aes(time, est, color=event)) + ggplot2::facet_wrap(~forcats::fct_rev(group))
  } else {
    pl <- ggplot2::ggplot(df, ggplot2::aes(time, est, color=event, linetype=group))
  }
  if (conf.int) {
    #in this line the line type around the confidence interval can be defined. ALso the intensity of the shaped area can be controled by alpha
    pl <- pl + ggplot2::geom_ribbon(ggplot2::aes(ymin = est - coef*std, ymax=est + coef*std, fill = event), alpha = 0.0, size=.2,linetype=2)
  }
  pl +
    ggplot2::geom_line()
}
#' Copy of ggcompetingrisks but needed to enable correction in a subfunction
#'
#' @param fit see ggcompetingrisks {survminer}
#' @param gnames see ggcompetingrisks {survminer}
#' @param gsep see ggcompetingrisks {survminer}
#' @param multiple_panels see ggcompetingrisks {survminer}
#' @param ggtheme see ggcompetingrisks {survminer}
#' @param coef see ggcompetingrisks {survminer}
#' @param conf.int see ggcompetingrisks {survminer}
#' @param ... see ggcompetingrisks {survminer}
#' @keywords internal
#' @return Returns an object of class gg.
#' @export
#'
#'
ggcompetingrisks_narlal <- function(fit, gnames = NULL, gsep=" ",
                                    multiple_panels = TRUE,
                                    ggtheme = survminer::theme_survminer(),
                                    coef = 1.96, conf.int = FALSE, ...) {
  stopifnot(any(class(fit) %in% c("cuminc")))

  if (any(class(fit) == "cuminc")) {
    pl <- ggcompetingrisks.cuminc_narlal(fit = fit, gnames=gnames,
                                  gsep=gsep, multiple_panels=multiple_panels,
                                  coef = coef, conf.int = conf.int)
  }
  pl <- pl + ggtheme +
    ggplot2::ylab("Probability of an event") + ggplot2::xlab("Time") +
    ggplot2::ggtitle("Cumulative incidence functions")
  ggpubr::ggpar(pl, ...)
}
