#' custom_tab_Narlal
#' @description An internal function used to define the layout of the tables generated by the package
#' @param df the data.frame containing the table
#' @param header the text that will appear as header of the table
#' @param footer the text that will appear as footer of the table
#' @keywords internal
#' @return a flextable containing the table
#' @export
#' @importFrom tibble %>%

custom_tab_Narlal <- function(df, header, footer=c()){
  flextable::flextable(df) %>%
    flextable::add_header_lines(header) %>%
    flextable::add_footer_lines(footer) %>%
    flextable::bold(i = 1, part = "header") %>%
    flextable::hline_top(part = "header",
              border = officer::fp_border(color = "black",
                                 width = 2,
                                 style = "solid")) %>%
    flextable::hline(i = 1,
          part = "header",
          border = officer::fp_border(color = "black",
                             width = 0.25,
                             style = "solid")) %>%
    flextable::hline_top(part = "body",
              border = officer::fp_border(color = "black",
                                 width = 0.25,
                                 style = "solid")) %>%
    flextable::hline_bottom(part = "body",
                 border = officer::fp_border(color = "black",
                                    width = 0.25,
                                    style = "solid")) %>%
    flextable::hline_bottom(part = "footer",
                 border = officer::fp_border(color = "black",
                                    width = 0.25,
                                    style = "solid")) %>%
    flextable::border_inner_h(part = "body",
                   border = officer::fp_border(color = "black",
                                      width = 0.25,
                                      style = "dotted")) %>%
    flextable::autofit(part = "body") %>%
    flextable::bg(part = "body", bg = "#f5f5f5") %>%
    flextable::align(part = "all", align = "center") %>%
    flextable::align(j = 1, part = "all", align = "left")
}
#' customtab_defaults_Narlal
#' @description An internal function used to define the defaults for the flextable used to produce the table of the package
#' @keywords internal
#' @return no direct returned values. Only setting flextable defaults
#' @export

customtab_defaults_Narlal <- function(){
  flextable::set_flextable_defaults(font.family = "Calibri",
                         font.size = 10,
                         border.color = "black")
}

ChageLabels_ggplot<-function(p,ChangeText=c()){
  if ("ChangeLabels" %in% names(ChangeText)){
    ChangeLabels<-ChangeText$ChangeLabels
  } else{
    ChangeLabels<-vector(mode='character',length=0)
  }
  if (any(names(p)=="labels")){
    for (j in seq_along(p$labels)){
      if (class(p$labels[[j]])[1]=="character"){
        newlabel<-as.character(ChangeLabels[p$labels[[j]]])
        if (!is.na(newlabel)){
          p$labels[j]<-newlabel
        }
      }
    }
  }
  return(p)
}
ChangeVar_vector<-function(x,ChangeText=c()){
  if ("ChangeVar" %in% names(ChangeText)){
    ChangeVar<-ChangeText$ChangeVar
  } else{
    ChangeVar<-vector(mode='character',length=0)
  }
  for (i in seq_along(x)){
    newvar<-as.character(ChangeVar[x[i]])
    if (!is.na(newvar)){
      x[i]<-newvar
    }
  }
  return(x)
}
ChangeLevel_vector<-function(x,ChangeText=c()){
  if ("ChangeLevels" %in% names(ChangeText)){
    ChangeLevels<-ChangeText$ChangeLevels
  } else{
    ChangeLevels<-vector(mode='character',length=0)
  }
  for (i in seq_along(x)){
    newlevel<-as.character(ChangeLevels[x[i]])
    if (!is.na(newlevel)){
      x[i]<-newlevel
    }
  }
  return(x)
}
ChageVarAndLevels_dataframe<-function(df,ChangeText=c()){
  if ("ChangeVar" %in% names(ChangeText)){
    ChangeVar<-ChangeText$ChangeVar
  } else{
    ChangeVar<-vector(mode='character',length=0)
  }
  if ("ChangeLevels" %in% names(ChangeText)){
    ChangeLevels<-ChangeText$ChangeLevels
  } else{
    ChangeLevels<-vector(mode='character',length=0)
  }
  tempcolnames<-colnames(df)
  for (i in seq_along(tempcolnames)){
    newvar<-as.character(ChangeVar[tempcolnames[i]])
    if (is.na(newvar)){
      newvar<-tempcolnames[i]
    }
    names(df)[names(df) == tempcolnames[i]] <- newvar
  }
  tempcolnames<-colnames(df)
  for (i in seq_along(tempcolnames)){
    if (is.factor(df[,i])){
      templevels<-levels(df[,i])
      newlabels<-c()
      for (j in seq_along(templevels)){
        newlabel<-as.character(ChangeLevels[templevels[j]])
        if (is.na(newlabel)){
          newlabel<-templevels[j]
        }
        newlabels<-c(newlabels,newlabel)
      }
      levels(df[,i])<-newlabels
    }
  }
  return(df)
}
